
import { MaintenanceCategory, MaintenanceItem } from './types';

export const INITIAL_MAINTENANCE_SCHEDULE: MaintenanceItem[] = [
  {
    id: 'engine-oil',
    category: MaintenanceCategory.OIL_LUBE,
    name: 'Engine Oil Change',
    intervalKm: 2000,
    description: 'Every 1,500 - 2,000 km',
    action: 'Change',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'gear-oil',
    category: MaintenanceCategory.OIL_LUBE,
    name: 'Gear Oil Change',
    intervalKm: 4000,
    description: 'Every 2nd Engine Oil Change',
    action: 'Change',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'cvt-cleaning',
    category: MaintenanceCategory.DRIVE_SYSTEM,
    name: 'CVT Cleaning (Full)',
    intervalKm: 5000,
    description: 'Every 5,000 km',
    action: 'Clean',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'cvt-filter',
    category: MaintenanceCategory.DRIVE_SYSTEM,
    name: 'CVT Filter (Small)',
    intervalKm: 2000,
    description: 'Clean @ 2k, Replace @ 10k',
    action: 'Clean',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'v-belt',
    category: MaintenanceCategory.DRIVE_SYSTEM,
    name: 'V-Belt (Drive Belt)',
    intervalKm: 10000,
    description: 'Check @ 10k, Replace @ 20k',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'flyball',
    category: MaintenanceCategory.DRIVE_SYSTEM,
    name: 'Flyball / Roller Weights',
    intervalKm: 5000,
    description: 'Check @ 5k (Replace if flat)',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'air-filter',
    category: MaintenanceCategory.AIR_SYSTEM,
    name: 'Air Filter',
    intervalKm: 5000,
    description: 'Check @ 5k, Replace @ 10k',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'coolant-check',
    category: MaintenanceCategory.FLUIDS,
    name: 'Coolant Level Check',
    intervalMonths: 1,
    description: 'Check monthly (Radiator reservoir)',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'coolant-flush',
    category: MaintenanceCategory.FLUIDS,
    name: 'Coolant Flush',
    intervalKm: 10000,
    description: 'Drain and refill every 10k',
    action: 'Flush',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'brake-fluid',
    category: MaintenanceCategory.FLUIDS,
    name: 'Brake Fluid',
    intervalMonths: 24,
    description: 'Flush every 2 years (Should not be Gray)',
    action: 'Flush',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'brake-pads-front',
    category: MaintenanceCategory.BRAKES,
    name: 'Front Brake Pads',
    intervalMonths: 1,
    description: 'Check Monthly / Replace if thin',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'brake-shoe-rear',
    category: MaintenanceCategory.BRAKES,
    name: 'Rear Brake Shoe',
    intervalMonths: 1,
    description: 'Check Monthly / Adjust tension',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'spark-plug',
    category: MaintenanceCategory.ELECTRICAL,
    name: 'Spark Plug',
    intervalKm: 10000,
    description: 'Replace every 10,000 km',
    action: 'Change',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'battery-health',
    category: MaintenanceCategory.ELECTRICAL,
    name: 'Battery Health',
    intervalMonths: 1,
    description: 'Check voltage (Should be 12.4V+)',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'tire-pressure',
    category: MaintenanceCategory.TIRES,
    name: 'Tire Pressure',
    intervalMonths: 0.25, 
    description: 'Weekly (29 PSI F / 33 PSI R)',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'tire-tread',
    category: MaintenanceCategory.TIRES,
    name: 'Tire Tread / Condition',
    intervalMonths: 1,
    description: 'Check for cracks or thinning',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'throttle-body',
    category: MaintenanceCategory.CLEANING,
    name: 'FI / Throttle Body Cleaning',
    intervalKm: 12500,
    description: 'Every 10,000 - 15,000 km',
    action: 'Clean',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'valve-clearance',
    category: MaintenanceCategory.MECHANICAL,
    name: 'Valve Clearance (Tappet)',
    intervalKm: 15000,
    description: 'Every 15,000 km (Full Tune-up)',
    action: 'Check',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  },
  {
    id: 'chassis-lube',
    category: MaintenanceCategory.MECHANICAL,
    name: 'Chassis / Pivot Lubrication',
    intervalKm: 5000,
    description: 'Every 5k (Grease stand and levers)',
    action: 'Clean',
    lastServiceOdo: 0,
    lastServiceDate: new Date().toISOString(),
  }
];
